version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/manage_fastapi/templates/project/{{ cookiecutter.folder_name }}/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
